#!/bin/sh

lock() {
    image="/tmp/i3lock.png"
    rm $image
    scrot $image
    convert $image -blur "0x8" $image
    i3lock -i $image
}

case "$1" in
    lock)
	# option=`dmenuPrompt "are you sure to LOCK?" "no\nyes"`
	option=`rofiPrompt "are you sure to LOCK?" "no\nyes" 2`
	if [[ $option == "yes" ]]
	then
	  lock
	fi
	;;

    logout)
        # option=`dmenuPrompt "are you sure to LOGOUT?" "no\nyes"`
     	option=`rofiPrompt "are you sure to LOGOUT?" "no\nyes" 2`
    	if [[ $option == "yes" ]]
   	then
		exit
    	fi
        ;;

    suspend)
        #lock && systemctl suspend
	# option=`dmenuPrompt "are you sure to SUSPEND?" "no\nyes"`
	option=`rofiPrompt "are you sure to SUSPEND?" "no\nyes" 2`
    	if [[ $option == "yes" ]]
   	then
		lock && systemctl suspend
    	fi
        ;;

    hibernate)
        #lock && systemctl hibernate
	# option=`dmenuPrompt "are you sure to HIBERNATE?" "no\nyes"`
	option=`rofiPrompt "are you sure to HIBERNATE?" "no\nyes" 2`
    	if [[ $option == "yes" ]]
   	then
		lock && systemctl hibernate
    	fi
        ;;

    reboot)
        #systemctl reboot
	# option=`dmenuPrompt "are you sure to REBOOT?" "no\nyes"`
	option=`rofiPrompt "are you sure to REBOOT?" "no\nyes" 2`
    	if [[ $option == "yes" ]]
   	then
	        systemctl reboot
    	fi
        ;;

    shutdown)
	# option=`dmenuPrompt "are you sure to SHUTDOWN?" "no\nyes"`
	option=`rofiPrompt "are you sure to SHUTDOWN?" "no\nyes" 2`
	if [[ $option == "yes" ]]
	then
		systemctl poweroff
	fi
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
