#!/bin/sh

# this requires i3lock-blur to be installed from AUR
lock() {
    # i3lock -f
    rm /tmp/i3lock.png
    image="/tmp/i3lock.png"
    scrot $image
    convert $image -blur "2x8" $image
    i3lock -i $image
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock && systemctl suspend
        ;;
    hibernate)
        lock && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
